namespace SpriteKind {
    export const meal = SpriteKind.create()
    export const helper = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .............fffcc..................
        .............fbbddc.................
        ..............fbbddfffffffff........
        ..............fcbcfbbbbbbbbbf.......
        ...........ffffccbbffb111cbbf.......
        ccccc....ffcccbbbbbff111111bf.......
        cbbbdc..fccccbbcbcbb1133cc1f........
        .cbbddcfcccccbcbcbbb1c131ccf........
        ..fbbdbccccccbcbcbbb111111f.........
        ..fcbbccccccccbbbbb1111111f.........
        ..fccbffcccccccbbbb111111f..........
        .fcbbf.cbdbcccccbbbc1111c...........
        .fbbf...cddddddfbbbc11cc............
        fbbf.....ccdddfbbdbffc..............
        fff........ccfbbdbf.................
        .............fffff..................
        `,img`
        ...........fffcc....................
        ...........fbbbbcfffffffff..........
        ............fbfffbbbbbbbbbf.........
        ............ffbbbbffb111bbf.........
        ..........ffcbbbbbff11111bf.........
        .........fcccbcbcbb11cccc1f.........
        ccccc...fcccbcbcbbb1c1c1cf2222......
        cbbddccfccccbcbcbbb1333c224442......
        .ccbddbcccccbbbbbbb1c333c24542......
        ..ccbbcccccccbbbbb11c133c24442......
        ..fccbffccccccbbbb111c31cc2222......
        ..fccf.cbbcccccbbbc111111c..........
        .fcbbf..cdddddfbbbc1111cc...........
        .fbbf....cdddfbbdbffccc.............
        fbbf......ccfbbdbf..................
        fff.........fffff...................
        `,img`
        ..........fffcc...fffffff...........
        ..........fbbbbcffbbbbbbbf..........
        ...........fbffbbbbb111bbf..........
        ...........ffbbbbff11111bf..........
        .........ffcbbbbbff1cccc1f..........
        ........fcccbcbcbb1c1c1cff..........
        ccccc..fcccbcbcbbb1333ccf22222......
        cbbddcfccccbcbcbbb1c333c244442......
        .ccbddcccccbbbbbbb1c333c245542......
        ..ccbbccccccbbbbb11c333c244542......
        ..fccbfccccccbbbb11c133cc24442......
        ..fccfcbbcccccbbbc11c31cc22222......
        .fcbbf.cdddddfbbbc111111c...........
        .fbbf...cdddfbbdbf1111cc............
        fbbf.....ccfbbdbfffccc..............
        fff........fffff....................
        `,img`
        ...........fffcc....................
        ...........fbbbbcfffffffff..........
        ............fbfffbbbbbbbbbf.........
        ............ffbbbbffb111bbf.........
        ..........ffcbbbbbff11111bf..22.2...
        .........fcccbcbcbb11cccc1f.222222..
        ccccc...fcccbcbcbbb1c1c1cf.2244442..
        cbbddccfccccbcbcbbb1333c...22455422.
        .ccbddbcccccbbbbbbb1c333c..22444422.
        ..ccbbcccccccbbbbb11c133c.22222222..
        ..fccbffccccccbbbb111c31cc...2222...
        ..fccf.cbbcccccbbbc111111c..........
        .fcbbf..cdddddfbbbc1111cc...........
        .fbbf....cdddfbbdbffccc.............
        fbbf......ccfbbdbf..................
        fff.........fffff...................
        `,img`
        .............fffcc..................
        .............fbbddc.................
        ..............fbbddfffffffff........
        ..............fcbcfbbbbbbbbbf.......
        ...........ffffccbbffb111cbbf.......
        ccccc....ffcccbbbbbff111111bf.......
        cbbbdc..fccccbbcbcbb1133cc1f........
        .cbbddcfcccccbcbcbbb1c131ccf....2222
        ..fbbdbccccccbcbcbbb111111f.....2444
        ..fcbbccccccccbbbbb1111111f.....2455
        ..fccbffcccccccbbbb111111f......2455
        .fcbbf.cbdbcccccbbbc1111c.......2222
        .fbbf...cddddddfbbbc11cc............
        fbbf.....ccdddfbbdbffc..............
        fff........ccfbbdbf.................
        .............fffff..................
        `,img`
        ..................fffcc.............
        ..................fcbddcc...........
        ...................fbbddcc..........
        ...................fcbbccf..........
        ......ccc.........ffccccccfffff.....
        ......cbbcc....fffcbbbbcbbbbbbbff...
        .......cbbdc.ffcccbbbbcbcbbbbbbbbf..
        .......fbbdcfcccccbbbcbcbbffbbbbbbff
        ........fbbffcccccbbbbbcb1ff11bbbcbf
        ........fcbbcccccccbbbbb11111111bbbf
        ........fcccccccccccbbbb11cc33111bf.
        .......fcbbffbdbcccccbbb111c13cccf.2
        .......fbbf..ccddddcfbbbc111c31cf..2
        ......fbbf.....ccdccbbdbf111cccf...2
        ......fff........ccbbdcfcccc.......2
        ..................fffff.............
        `,img`
        ....................................
        ....................................
        ....................................
        ...............ffffcc...............
        ...............fbbbddc..............
        ................fbbbddcffffff.......
        ccccc.......fffcbbbbbbbbbbbbbff.....
        cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
        .cbbddcfffcccccbbbbcbbcbbbbbbbbbbf..
        ..fbbdbccccccccbbbbcbcbbbbbbbbbbcbf.
        ..fcbbccccccccccbbbbbcbbfffbbbbbbbf.
        ..fccbffcbcccccccbbbbcbbfff1111bbff.
        .fcbbf..ccbbbccccccbbbb111111111ff.2
        fbbff.....cccbddfbbbdb111ccccccc....
        fff..........ccfbbbdbfcccccc........
        ...............ffffff...............
        `],
    100,
    false
    )
    timer.after(600, function () {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 4 4 . . . . . . . 
            . . . . . . 4 5 5 4 . . . . . . 
            . . . . . . 2 5 5 2 . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, 50, 0)
        projectile.setVelocity(400, 0)
    })
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.helper, function (sprite, otherSprite) {
    info.changeScoreBy(2)
    sprites.destroy(mySprite5)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.meal, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.trail, 1000)
    iambig = 0
    scaling.scaleToPercent(mySprite, 100, ScaleDirection.Uniformly, ScaleAnchor.Middle)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    scaling.scaleToPercent(mySprite, 250, ScaleDirection.Uniformly, ScaleAnchor.Middle)
    iambig = 1
    sprites.destroy(otherSprite, effects.trail, 1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(mySprite4, effects.fire, 500)
    info.changeLifeBy(-1)
})
let projectile: Sprite = null
let mySprite5: Sprite = null
let mySprite4: Sprite = null
let iambig = 0
let mySprite: Sprite = null
info.setScore(0)
info.setLife(5)
mySprite = sprites.create(img`
    ...........fffcc....................
    ...........fbbbbcfffffffff..........
    ............fbfffbbbbbbbbbf.........
    ............ffbbbbffb111bbf.........
    ..........ffcbbbbbff11111bf.........
    .........fcccbcbcbb11cccc1f.........
    ccccc...fcccbcbcbbb1c1c1cf..........
    cbbddccfccccbcbcbbb1333c............
    .ccbddbcccccbbbbbbb1c333c...........
    ..ccbbcccccccbbbbb11c133c...........
    ..fccbffccccccbbbb111c31cc..........
    ..fccf.cbbcccccbbbc111111c..........
    .fcbbf..cdddddfbbbc1111cc...........
    .fbbf....cdddfbbdbffccc.............
    fbbf......ccfbbdbf..................
    fff.........fffff...................
    `, SpriteKind.Player)
iambig = 0
tiles.setCurrentTilemap(tilemap`level1`)
controller.moveSprite(mySprite)
let mySprite2 = sprites.create(img`
    . . . . c c c c . . . . . . . . 
    . . . c d d d d c c . . . . . . 
    . . . c d c c c c c c . . . . . 
    c c . c c d 4 4 4 4 c c . . . . 
    c 4 c c 1 4 4 4 4 4 d 4 c . . . 
    f 4 c 1 d 4 4 4 4 1 4 4 4 c . . 
    f 4 4 1 4 4 4 4 4 1 4 4 4 4 c . 
    f 4 f 1 4 4 f c 1 1 4 4 4 4 4 f 
    f 4 f 1 4 4 f 4 c 1 4 f 4 4 4 f 
    f f f d 4 4 f 4 4 1 4 4 4 4 4 f 
    . . f f d 4 4 c c 1 4 4 4 4 f . 
    . . . f c 4 4 4 4 4 d 4 f f . . 
    . . c b d c 4 4 4 4 f f . . . . 
    . . c d d d f f f f . . . . . . 
    . . . c c c . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
scene.cameraShake(8, 5000)
mySprite.setPosition(8, 16)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, assets.tile`myTile4`)
let mySprite3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . c c c c c . . . . . . . . 
    . . c 5 5 5 5 5 c c . . . . . . 
    . c 5 5 5 5 5 5 5 5 c . . . . . 
    . c 5 5 5 b b b b b b c . . . . 
    . . c c b b 1 b b 1 1 c . . . . 
    . . . c 1 1 1 b b 1 1 1 c . . . 
    c c . c 1 1 1 b 1 1 1 1 c . . . 
    c 5 b b 1 1 1 b 1 1 1 d c . . . 
    c 5 5 5 1 b 1 b 1 c 1 d c c . . 
    c 5 b b 1 b 1 1 1 1 1 d d c c . 
    c c . f 1 b b 1 1 1 1 1 d d d f 
    . . . f b b b 1 1 1 1 1 1 f f f 
    . . f 5 5 b b b 1 1 1 f f . . . 
    . . f 5 5 5 5 5 f f f . . . . . 
    . . f f f f f f . . . . . . . . 
    `, SpriteKind.meal)
mySprite3.setPosition(146, 14)
mySprite4 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . b d b . . . . . . 
    . . . . . . . b d b c . . . . . 
    . . . . b b c 5 5 5 c b b . . . 
    . . . . b 5 5 5 1 5 5 5 b . . . 
    . . . c c 5 5 5 1 5 5 5 c c . . 
    . . b b 5 5 5 1 1 1 5 5 5 b b . 
    . . d d 5 1 1 1 1 1 1 1 5 d d . 
    . . b b 5 5 5 1 1 1 5 5 5 b b . 
    . . . c c 5 5 5 1 5 5 5 c c . . 
    . . . . b 5 5 5 1 5 5 5 b . . . 
    . . . . b b c 5 5 5 c b b . . . 
    . . . . . . c b d b c . . . . . 
    . . . . . . . b d b . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
mySprite4.follow(mySprite, 50)
mySprite4.setPosition(8, 108)
mySprite5 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . c c . . . . . . . . . . . 
    . . c 3 6 c c c c . . . . . . . 
    . . c 6 3 3 3 3 6 c . . . . . . 
    . c 3 3 3 3 3 c c 6 c . c c . . 
    c 3 3 3 3 3 c 5 5 c 6 c 5 5 c . 
    c c 3 3 3 6 f f 5 c 6 c 5 f f . 
    c c 6 6 6 6 f f 5 3 c 3 5 f f . 
    c 3 3 3 3 3 3 c 5 5 3 5 5 b . . 
    c 3 3 3 3 c c b 5 5 5 5 5 c c . 
    . c 3 3 c 5 5 b 4 5 5 5 4 5 5 c 
    . . b b c 5 b b 4 4 4 4 b 4 5 b 
    . c 5 c 4 c 5 5 5 c 4 c 5 5 5 c 
    . c 5 c 4 c 5 5 5 5 c 5 5 5 5 c 
    . c c c . . c c c c c c c c c . 
    `, SpriteKind.helper)
